### ISSUE TITLE
perl-json-xs (missing):

### ISSUE THREAD

**Issue by sjsaleem** [shuaiscott/zap2xml#4]
Step 9/15 : RUN apk add --no-cache perl@edge perl-html-parser@edge perl-http-cookies@edge perl-lwp-useragent-determined@edge perl-json@edge perl-json-    xs@edgetesting
 ---> Running in 8ec5a767d434
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/armhf/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armhf/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/armhf/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
ERROR: unsatisfiable constraints:
  perl-json-xs (missing):
    required by: world[perl-json-xs]
The command '/bin/sh -c apk add --no-cache perl@edge perl-html-parser@edge perl-http-cookies@edge perl-lwp-useragent-determined@edge perl-json@edge pe    rl-json-xs@edgetesting' returned a non-zero code: 1

Can you please let me know how to fix this issue?

**Comment by shuaiscott** [comment]
Updated `Dockerfile` with most recent version of alpine and fixed perl-json-xs in commit dc196fe

New image available @ https://hub.docker.com/r/shuaiscott/zap2xml
