### ISSUE TITLE
Script Failing with invalid csrf token

### ISSUE THREAD

**Issue by bjs-pdx** [shuaiscott/zap2xml#5]
Been using zap2xml.pl for years but a couple of days ago it started failing with "invalid csrf token" message.  Nothing changed on my end so wondering if there is any solution for this?

**Comment by shuaiscott** [comment]
I'll be honest, I haven't used this for like 2-3 years, so not sure off the top of my head what's going on... but I'll try to take a look 😄

**Comment by shuaiscott** [comment]
#2

**Comment by shuaiscott** [comment]
@bjs-pdx I just pushed a new version with the latest code we have for zap2xml... Could you please pull that and try it?

https://hub.docker.com/r/shuaiscott/zap2xml

**Comment by bjs-pdx** [comment]
Sorry to take so long getting back to you.  Strangely just a couple of days after the script failed it mysteriously started working again.  Can't say for sure but there must have been some issue with the Zap2It website causing problems.  I posted about this on the Plex forums and others had the same problem which also mysteriously went away.  Since everything is working again I'm going to leave things alone for now.  Thanks for  your quick response.
